Template project for JDN with Selenide
jdi-templates/jdn-template-selenide pull request #1
Opened 2023-12-26 23:08 UTC by spbqaru

Template project for JDN with Selenide

2024-01-05 16:04 UTC, pnatashap requested changes

2024-01-05 16:04 UTC, pnatashap commented on pom.xml
> +    <profiles>
эти параметры нужны для aspectj, тут не нужны

2024-01-05 16:04 UTC, pnatashap commented on pom.xml
> +            <artifactId>testng</artifactId>
дубль

2024-01-05 16:04 UTC, pnatashap commented on pom.xml
> +                    <source>11</source>
видимо можно скинуть на 8, testng ты взял для 8

2024-01-05 16:04 UTC, pnatashap commented on pom.xml
> +                        ${aspectj.args}
не нужен этот параметр

2024-01-05 16:04 UTC, pnatashap commented on pom.xml
> +                        <groupId>org.aspectj</groupId>
а оно точно надо?

2024-01-05 16:04 UTC, pnatashap commented on src/test/java/test/BaseTest.java
> +        Configuration.baseUrl = "https://www.example.com";
а зачем jdi в pom?

2024-01-05 16:04 UTC, pnatashap commented on src/test/java/test/BaseTest.java
> +        Configuration.browser = "chrome"; // You can also use "firefox", "edge", etc.
из параметров сразу тогда лучше

2024-01-05 16:04 UTC, pnatashap commented on src/test/resources/testng.xml
> +<?xml version="1.0" encoding="WINDOWS-1251"?><!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
давай не будем виндовую кодировку вставлять, пусть будет UTF-8

2024-01-08 12:51 UTC, spbqaru commented on pom.xml
> +    <profiles>
убрал

2024-01-08 12:51 UTC, spbqaru commented on pom.xml
> +            <artifactId>testng</artifactId>
удалил

2024-01-08 12:52 UTC, spbqaru commented on pom.xml
> +                    <source>11</source>
скинул

2024-01-08 12:52 UTC, spbqaru commented on pom.xml
> +                        ${aspectj.args}
удалил

2024-01-08 12:52 UTC, spbqaru commented on pom.xml
> +                        <groupId>org.aspectj</groupId>
не надо. удалил

2024-01-08 12:52 UTC, spbqaru commented on src/test/java/test/BaseTest.java
> +        Configuration.baseUrl = "https://www.example.com";
убрал

2024-01-08 12:53 UTC, spbqaru commented on src/test/java/test/BaseTest.java
> +        Configuration.browser = "chrome"; // You can also use "firefox", "edge", etc.
убрал из pom

2024-01-09 00:22 UTC, pnatashap requested changes
еще было бы хорошо иметь github action для запуска и проверки, что оно работает, чтобы не скачивать себе

2024-01-09 00:22 UTC, pnatashap commented on pom.xml
> +    <profiles>
все еще на месте

2024-01-16 12:46 UTC, spbqaru commented on src/test/resources/testng.xml
> +<?xml version="1.0" encoding="WINDOWS-1251"?><!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
заменил на UTF-8

2024-01-23 12:30 UTC, spbqaru commented on pom.xml
> +    <profiles>
точно убрал

2024-01-23 12:37 UTC, spbqaru commented
> еще было бы хорошо иметь github action для запуска и проверки, что оно работает, чтобы не скачивать себе

добавлены ACTIONS
https://github.com/jdi-templates/jdn-template-selenide/actions/workflows/build.yml

2024-01-23 13:11 UTC, merged